name: Check versions
on:
  issues:
    types: [opened]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: react-navigation/check-versions-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          optional-packages: |
            @react-navigation/native
            @react-navigation/stack
          required-packages: |
            react-native
            react
          missing-versions-label: 'needs more info'
